---
- include_vars: aws.yml

- local_action: 
    module: ec2
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_os_image }}" 
    wait: yes
    count_tag:
    - class: "{{ ec2_count_tag }}"
    exact_count: "{{ ec2_count }}"
    region: "{{ ec2_region }}"
    instance_tags: "{{ ec2_tags }}" 
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    key_name: "{{ ec2_public_key }}"
    group: "{{ ec2_security_group }}"
  register: ec2

- name: Add all instance public IPs to host group
  add_host: name={{ item.public_ip }} group=tag_class_{{ ec2_count_tag }}  ansible_ssh_user={{ ec2_os_image_user }}ubuntu
  with_items: ec2.instances

- name: Wait for SSH to come up
  wait_for: host={{ item.public_ip }} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances

